/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Beans.Produto;
import Util.JPAUtil;
import Util.SideMenuUtil;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Query;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class FormListaProdutos extends javax.swing.JFrame {
    
    FormMenu menu;
    SideMenuUtil sideMenu = new SideMenuUtil();
//    private DefaultTableModel model;
    String acesso = "Administrador";
    
//    List<Produto> lista1 = getAllUsuarios();
    
    //ACT3 done
    
    
    //Construtor somente acessivel por Atendente atraves de login
    public FormListaProdutos(String acesso) {
        initComponents();
        subPanelVendas.setVisible(false);
        subPanelClientes.setVisible(false);
        subPanelProdutos.setVisible(false);
        btnListaProduto1.setEnabled(false);
        
        //acesso Atendente,  caixa wont get here, admin is god
        if(acesso.equals("Atendente")){
            btnClientes.setEnabled(false);
            btnProdutos.setEnabled(false);
            btnVendas.setEnabled(false);
            btnMudarPreco.setVisible(false);
            btnMenu.setVisible(false);
        }
        
        this.acesso=acesso;
        //listar();
        displayTable(getAllProdutos());
    }
    
    //Construtor p/ Admin to set Menu visible again later
    public FormListaProdutos(FormMenu menu) {
        initComponents();
        subPanelVendas.setVisible(false);
        subPanelClientes.setVisible(false);
        subPanelProdutos.setVisible(false);
        btnListaProduto1.setEnabled(false);
        
        this.menu=menu;
                
        
        displayTable(getAllProdutos());
        //listar();
    }
    
    //Construtor btnSalvar de mudança de estoque somente acessivel a Admin
    public FormListaProdutos(double novoPreco, int row) {
        initComponents();
        subPanelVendas.setVisible(false);
        subPanelClientes.setVisible(false);
        subPanelProdutos.setVisible(false);
        btnListaProduto1.setEnabled(false);
        
        
        // change value at table Proof of concept
        jTable1.getModel().setValueAt(novoPreco, row, 2);

        displayTable(getAllProdutos());
        //listar();
    }
    


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        subPanelClientes = new javax.swing.JPanel();
        btnCadCliente1 = new javax.swing.JButton();
        btnListaCliente1 = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        subPanelProdutos = new javax.swing.JPanel();
        btnCadProduto1 = new javax.swing.JButton();
        btnListaProduto1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        subPanelVendas = new javax.swing.JPanel();
        btnCaixa = new javax.swing.JButton();
        btnListaVenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMudarPreco = new javax.swing.JButton();
        btnTamanhos = new javax.swing.JButton();
        txtBuscaNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        SidePanel.setBackground(new java.awt.Color(51, 0, 153));

        btnMenu.setBackground(new java.awt.Color(169, 200, 231));
        btnMenu.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnMenu.setText("MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(174, 43, 43));
        btnSair.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(169, 200, 231));
        btnClientes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setAlignmentX(0.5F);
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnVendas.setBackground(new java.awt.Color(169, 200, 231));
        btnVendas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnVendas.setText("VENDAS");
        btnVendas.setAlignmentX(0.5F);
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });

        subPanelClientes.setBackground(new java.awt.Color(51, 0, 153));

        btnCadCliente1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadCliente1.setText("Cadastro de Clientes");
        btnCadCliente1.setBorder(null);
        btnCadCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCliente1ActionPerformed(evt);
            }
        });

        btnListaCliente1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnListaCliente1.setText("Lista de Clientes");
        btnListaCliente1.setBorder(null);
        btnListaCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelClientesLayout = new javax.swing.GroupLayout(subPanelClientes);
        subPanelClientes.setLayout(subPanelClientesLayout);
        subPanelClientesLayout.setHorizontalGroup(
            subPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListaCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        subPanelClientesLayout.setVerticalGroup(
            subPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelClientesLayout.createSequentialGroup()
                .addComponent(btnCadCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListaCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnProdutos.setBackground(new java.awt.Color(169, 200, 231));
        btnProdutos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnProdutos.setText("PRODUTOS");
        btnProdutos.setAlignmentX(0.5F);
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        subPanelProdutos.setBackground(new java.awt.Color(51, 0, 153));

        btnCadProduto1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadProduto1.setText("Cadastro de Produtos");
        btnCadProduto1.setBorder(null);
        btnCadProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProduto1ActionPerformed(evt);
            }
        });

        btnListaProduto1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnListaProduto1.setText("Lista de Produtos");
        btnListaProduto1.setBorder(null);

        javax.swing.GroupLayout subPanelProdutosLayout = new javax.swing.GroupLayout(subPanelProdutos);
        subPanelProdutos.setLayout(subPanelProdutosLayout);
        subPanelProdutosLayout.setHorizontalGroup(
            subPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        subPanelProdutosLayout.setVerticalGroup(
            subPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelProdutosLayout.createSequentialGroup()
                .addComponent(btnCadProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListaProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoe-200-200.jpg"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);

        subPanelVendas.setBackground(new java.awt.Color(51, 0, 153));
        subPanelVendas.setForeground(new java.awt.Color(255, 255, 255));

        btnCaixa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCaixa.setText("Controle de Caixa");
        btnCaixa.setBorder(null);
        btnCaixa.setPreferredSize(new java.awt.Dimension(42, 15));
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });

        btnListaVenda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnListaVenda.setText("Histórico de Vendas");
        btnListaVenda.setBorder(null);
        btnListaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelVendasLayout = new javax.swing.GroupLayout(subPanelVendas);
        subPanelVendas.setLayout(subPanelVendasLayout);
        subPanelVendasLayout.setHorizontalGroup(
            subPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        subPanelVendasLayout.setVerticalGroup(
            subPanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelVendasLayout.createSequentialGroup()
                .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(subPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subPanelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subPanelVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanelVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanelProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(231, 231, 231));
        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Listagem e Estoque");

        btnMudarPreco.setBackground(new java.awt.Color(255, 165, 0));
        btnMudarPreco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMudarPreco.setText("Mudar Preço");
        btnMudarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudarPrecoActionPerformed(evt);
            }
        });

        btnTamanhos.setBackground(new java.awt.Color(255, 165, 0));
        btnTamanhos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnTamanhos.setText("Tamanhos");
        btnTamanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamanhosActionPerformed(evt);
            }
        });

        txtBuscaNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBuscaNome.setText("Corrida");
        txtBuscaNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaNomeCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Busca nome:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nomel1", "marc1", "100", "cat1", "gen1", "sim"},
                {"nome2", "marc2[", "200", "cat2", "gen2", "não"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Marca", "Preço", "Categoria", "Genero", "Em estoque"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnTamanhos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMudarPreco)
                        .addGap(130, 130, 130)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMudarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTamanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        FormLogin tela = new FormLogin();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed

        //shows sub panel form selected button and hides the others
        sideMenu.enablePanel(subPanelClientes, subPanelProdutos, subPanelVendas);

        //change color of button when pressed, first will highlight the others will reset to default
        sideMenu.styleButton2(btnClientes, btnProdutos, btnVendas);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed

        //shows sub panel form selected button and hides the others
        sideMenu.enablePanel(subPanelVendas, subPanelProdutos, subPanelClientes);

        //change color of button when pressed, first will highlight the others will reset to default
        sideMenu.styleButton2(btnVendas, btnProdutos, btnClientes);
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnCadCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCliente1ActionPerformed
        FormCadClientes tela = new FormCadClientes(menu);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadCliente1ActionPerformed

    private void btnListaCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaCliente1ActionPerformed
        FormListaClientes tela = new FormListaClientes(menu);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaCliente1ActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed

        //shows sub panel form selected button and hides the others
        sideMenu.enablePanel(subPanelProdutos, subPanelVendas, subPanelClientes);

        //change color of button when pressed, first will highlight the others will reset to default
        sideMenu.styleButton2(btnProdutos, btnVendas, btnClientes);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnCadProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProduto1ActionPerformed
        FormCadProdutos tela = new FormCadProdutos(menu);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadProduto1ActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        FormCaixa tela = new FormCaixa(menu);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnListaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaVendaActionPerformed
        FormListaVendas tela = new FormListaVendas(menu);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaVendaActionPerformed

    private void btnMudarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMudarPrecoActionPerformed
        
       try{
        DefaultTableModel modelTable = (DefaultTableModel) jTable1.getModel();
        Object obj = modelTable.getValueAt(jTable1.getSelectedRow(), 0);
        
    if (obj != null){
        
        String p = (obj.toString());
        String d = modelTable.getValueAt(jTable1.getSelectedRow(), 2).toString();
        int row = jTable1.getSelectedRow();
        
        
        
        FormListaProdutosPreco tela = new FormListaProdutosPreco(p,d,this,row);
        tela.setVisible(true);
        
        } else {
            JOptionPane.showMessageDialog(this, "Escolha uma linha");
        }
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Escolha uma linha");
        }
        
        
    }//GEN-LAST:event_btnMudarPrecoActionPerformed

    private void btnTamanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamanhosActionPerformed
        try{
        DefaultTableModel modelTable = (DefaultTableModel) jTable1.getModel();
        Object obj = modelTable.getValueAt(jTable1.getSelectedRow(), 0);
        
    if (obj != null){
        
        String nome = (obj.toString());
        
        
        
        FormListaProdutosTamanhos tela = new FormListaProdutosTamanhos(nome, acesso);
        tela.setVisible(true);
        
        } else {
            JOptionPane.showMessageDialog(this, "Escolha uma linha");
        }
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Escolha uma linha");
        }
    }//GEN-LAST:event_btnTamanhosActionPerformed


    //SELECT product by name dynamicaly
    private void txtBuscaNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaNomeCaretUpdate

        try {

            String searchText = txtBuscaNome.getText(); // Get the text from the field

            TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
            jTable1.setRowSorter(sorter);

            if (searchText.trim().length() == 0) {
                // If no text, show all rows
                sorter.setRowFilter(null);
            } else {
                try {
                    // Filter rows containing the search text
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
                } catch (PatternSyntaxException ex) {
                    JOptionPane.showMessageDialog(this, "Invalid search pattern!");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "AAAAAAAAAA");
        }


    }//GEN-LAST:event_txtBuscaNomeCaretUpdate

    
    public List<Produto> getAllProdutos() {
        EntityManager em = JPAUtil.conectar();
        Query query = em.createQuery("SELECT u FROM Produto u");
        return query.getResultList();
    }
    
        
        public void displayTable(List<Produto> usuarios) {
            
            try{
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    // Populate the table model with data from the Usuario list
    for (Produto produto : usuarios) {
        model.addRow(new Object[]{
            
            produto.getNome(),
            produto.getMarca(),
            String.valueOf(produto.getPreco()),
            produto.getCategoria(),
            produto.getGenero()
//            String.valueOf(produto.getEmEstoque())

        });
    }

    // Assign the model to the JTable
    jTable1.setModel(model);
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, "AAAAAAAAAA");
            }
}
    

        
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton btnCadCliente1;
    private javax.swing.JButton btnCadProduto1;
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnListaCliente1;
    private javax.swing.JButton btnListaProduto1;
    private javax.swing.JButton btnListaVenda;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMudarPreco;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTamanhos;
    private javax.swing.JButton btnVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel subPanelClientes;
    private javax.swing.JPanel subPanelProdutos;
    private javax.swing.JPanel subPanelVendas;
    private javax.swing.JTextField txtBuscaNome;
    // End of variables declaration//GEN-END:variables
}
